const questions = [
  'Who is the oldest?',
  'Who is the tallest?',
  'Who is the youngest?',
  'Who is the shortest?',
  'Who has the longest hair?',
  'Who has the shortest hair?',
  'Who was the last person to travel abroad?',
  'Who was the last person to buy a game?',
  'Who has the largest physical game collection?',
  'Who speaks the most languages?',
  'Who lost the last game?',
  'Who\'s birthday is earliest in the year?',
  'Who\'s birthday is latest in the year?',
  'Who has the most pets?',
];
